from decimal import Decimal
from typing import Protocol
from uuid import UUID
from bancocloud.domain.cards import Card


class CardRepository(Protocol):
    def list(self, customer_ref: UUID | None = None, account_ref: UUID | None = None) -> list[Card]: ...
    def get_for_update(self, card_ref: UUID) -> Card | None: ...
    def add_used_balance(self, card_ref: UUID, amount: Decimal) -> None: ...
    def purchase_credit(self, card_ref: UUID, amount: Decimal) -> Card: ...
