from typing import Protocol
from uuid import UUID


class CaseRepository(Protocol):
    def list_recent(self, limit: int = 100) -> list[dict]: ...
    def get_reference(self, case_id: UUID) -> tuple[str, str] | None: ...
    def save_decision(self, case_id: UUID, decision: dict) -> None: ...
